@api = http://localhost:3000/publi
@apisp = http://localhost:3000/usersp
@apiemail = http://localhost:3000/usersemail
@apiupdate = http://localhost:3000/user/update
@apicat = http://localhost:3000/categoria
@allapi = http://localhost:3000/all
@image = http://localhost:3000/profileimg
@updateimage = http://localhost:3000/user/updateImage


GET  {{image}}


GET {{api}}

###
GET  {{allapi}}
Content-Type: application/json

{
    "tabla": "tipo_ofertas"
}
###
GET {{apicat}}
###
POST {{apisp}}
Content-Type: application/json

{
    "username": "paolas",
    "email": "paolas@example.com",
    "password": "admin"
}
###
POST {{api}}
Content-Type: application/json

{
    "username": "pepe",
    "email": "pepe@example.com",
    "password": "1234"
}

###
POST {{api}}
Content-Type: application/json

{
    "email": "pepe@example.com",
    "password" : "1234"
}

###
GET  {{apiemail}}
Content-Type: application/json

{
    "email": "pepe@example.com",
    "password" : "1234"
}
###
PUT {{apiupdate}}
Content-Type: application/json

{
    "username" : "pepe", 
    "email" : "pepe@admin", 
    "nombre" : "pepe", 
    "apellido" : "pepom",
     "dni" : "aa", 
     "userId" : "24"
}
###
PUT {{updateimage}}
Content-Type: application/json

{
    "img" : "profileimg/profile_55.jpg",
    "userId" : "1"
}