@api = http://localhost:3000/publi
@apisp = http://localhost:3000/usersp
@apiemail = http://localhost:3000/usersemail

GET {{api}}

###
POST {{apisp}}
Content-Type: application/json

{
    "username": "paolas",
    "email": "paolas@example.com",
    "password": "admin"
}
###
POST {{api}}
Content-Type: application/json

{
    "username": "pepe",
    "email": "pepe@example.com",
    "password": "1234"
}

###
POST {{api}}
Content-Type: application/json

{
    "email": "pepe@example.com",
    "password" : "1234"
}

###
GET  {{apiemail}}
Content-Type: application/json

{
    "email": "pepe@example.com",
    "password" : "1234"
}